config/routes.rb
AdoptASidewalk::Application.routes.draw do
  resources :authentications

  devise_for :users, :controllers => {
      :passwords => 'passwords',
      :registrations => 'users',
      :sessions => 'sessions',
  } do
    get 'forgot_password' => 'passwords#forgot'
  end
  
  get 'address' => 'addresses#show', :as => 'address'
  get 'address_report' => 'addresses#report'
  get 'tos' => 'main#tos'
  get 'sidebar' => 'main#sidebar'

  match '/auth/:provider/callback' => 'authentications#create'
  
  resources :sidewalks do
    get 'find_closest', :on => :collection
  end
  resources :sidewalk_claims
  root :to => 'main#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :first_name, :last_name, :organization, :sms_number, :password, :password_confirmation, :remember_me
  validates_presence_of :first_name, :last_name
  has_many :sidewalk_claims
  has_many :authentications

  def short_name
    "#{first_name} #{last_name.chr}."
  end

  def fullname
    first_name + ' ' + last_name
  end

  def apply_omniauth(omniauth)
    self.first_name = omniauth[:info][:first_name] if first_name.blank?
    self.last_name = omniauth[:info][:last_name] if last_name.blank?
    self.email = omniauth[:info][:email] if email.blank?
    authentications.build(:provider => omniauth[:provider],
                          :uid => omniauth[:uid],
                          #:token => omniauth[:credentials][:token]
                          )
  end
  
  def password_required?
    (authentications.empty? || !password.blank?) && super
  end

end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  layout 'info_window'

  def new
    respond_with (@user = User.new)
  end

  def edit
    render :edit
  end

  def update
    if resource.update_with_password(params[resource_name])
      sign_in(resource_name, resource, :bypass => true)
      flash[:notice] = "Profile updated!"
      redirect_to(:controller => "info_window", :action => "index", :map_object_id => params[:map_object_id])
    else
      clean_up_passwords(resource)
      render(:json => {"errors" => resource.errors}, :status => 500)
    end
  end

  def create
    build_resource
    if verify_recaptcha
      if resource.save
        sign_in resource
        session[:omniauth] = nil unless @user.new_record?
        render :inline => "You have been registered!" and return
      else
        errors = resource.errors
      end
    else
      errors = "Invalid verification code."
    end

    #set_flash_message :notice, :inactive_signed_up, :reason => errors if is_navigational_format?
    flash.now[:error] = errors
    flash.delete(:recaptcha_error)
    
    clean_up_passwords(resource)
    render(:json => {"errors" => errors,
                    :html => render_to_string(:template => 'users/new.html.haml')},
                    :status => 500)
  end
  
  private
  
  def build_resource(*args)
    super
    if session[:omniauth]
      @user.apply_omniauth(session[:omniauth])
      @user.valid?
    end
  end  
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_profile.html.haml
= form_for :user, :url => edit_user_registration_path, :html => {:id => "edit_profile_form", :method => "get"} do |f|
  = f.submit t("buttons.edit_profile")

app/views/users/_reminder.html.haml
= form_for :reminder, :url => reminders_path, :html => {:id => "reminder_form", :method => "post"} do |f|
  = f.hidden_field "from_user_id", :value => current_user.id
  = f.hidden_field "to_user_id", :value => @thing.user.id
  = f.hidden_field "thing_id", :value => @thing.id
  = f.submit t("buttons.send_reminder")

app/views/users/create.html.haml
%h2= t("titles.registered")

app/views/users/edit.html.haml
= form_for resource, :as => resource_name, :url => registration_path(resource_name), :html => {:id => "edit_form", :method => :put} do |f|
  %h2
    = t("titles.edit_profile")
  = f.hidden_field "id"
  = f.label "email", t("labels.email"), :id => "user_email_label"
  %em
    = image_tag "lock.svg", :class => "lock", :alt => t("captions.private"), :title => t("captions.private")
  = f.text_field "email"
  = f.label "name", t("labels.name"), :id => "user_name_label"
  %em
    = t("captions.public")
  = f.text_field "name"
  = f.label "organization", t("labels.organization"), :id => "user_organization_label"
  %em
    = t("captions.public")
  = f.text_field "organization"
  = f.label "voice_number", t("labels.voice_number"), :id => "user_voice_number_label"
  %em
    = image_tag "lock.svg", :class => "lock", :alt => t("captions.private"), :title => t("captions.private")
  = f.text_field "voice_number"
  = f.label "sms_number", t("labels.sms_number"), :id => "user_sms_number_label"
  %em
    = image_tag "lock.svg", :class => "lock", :alt => t("captions.private"), :title => t("captions.private")
  = f.text_field "sms_number"
  = f.label "password", t("labels.password_new"), :id => "user_password_label"
  %em
    = t("captions.password")
  = f.password_field "password"
  = f.label "current_password", t("labels.current_password"), :id => "user_current_password_label"
  %em
    = t("captions.current_password")
  = f.password_field "current_password"
  = f.submit t("buttons.update")
= render :partial => 'things/back'

app/views/users/new.html.haml
- if defined?(devise_error_messages!)
  .error_msg
    = devise_error_messages! 

#sign_up_box
  = form_for :user, :url => user_registration_path, :html => {:id => "sign_up_form", :class => 'form'} do |f|
    %h2= t("titles.register_now")

    .signup
      %ul.horizontal_items
        %li
          = f.label :first_name, t("labels.first_name")
          = f.text_field :first_name
        %li
          = f.label :last_name, t("labels.last_name")
          = f.text_field :last_name
        %li
          = f.label :email, t("labels.email")
          = f.text_field :email, :value => params[:user] ? params[:user][:email] : nil
        %li
          = f.label :password, t("labels.password_reg")
          = f.password_field :password
        %li
          = f.label :password_confirmation, t("labels.password_confirm")
          = f.password_field :password_confirmation
      
      %h3{:style => 'margin-top: 15px;'}
        = t("labels.recaptcha")
      #recaptcha_box
        = recaptcha_tags :ajax => true
            
      %ul.horizontal_items.font_12.center{:style => 'margin-top: 15px;'}
        %li= f.submit t("buttons.register")
        %li
          .font_1.link_1
            = t("labels.user_existing")
            %br
            = link_to t("links.sign_in"), '#', :id => "sign_in_link"
      .font_12.link_1.center
        = t("defaults.tos", :tos => link_to(t("links.terms"), tos_path, :target => '_blank')).html_safe

app/views/users/profile.html.haml
%h2
  = t("titles.adopted", :thing_name => @thing.name ? @thing.name.titleize : t("defaults.this_thing", :thing => t("defaults.thing")))
  %br
  = t("titles.byline", :name => @thing.user.name)
  %br
  = t("titles.ofline", :organization => @thing.user.organization) unless @thing.user.organization.blank?
- if user_signed_in?
  = render :partial => 'users/reminder'
  = render :partial => 'users/edit_profile'
  = render :partial => 'sessions/sign_out'
- else
  = render :partial => 'sessions/sign_in'

app/views/users/thank_you.html.haml
%h2
  = t("titles.thank_you", :thing => t("defaults.thing"))
= render :partial => 'things/abandon'
= render :partial => 'users/edit_profile'
= render :partial => 'sessions/sign_out'